FROM ubuntu:22.04

ARG GCC=11
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y cmake ninja-build clang-format && \
    apt-get install -y gcc-${GCC} g++-${GCC} && \
    rm -rf /var/lib/apt/lists/*

ENV CC=gcc-${GCC} CXX=g++-${GCC}

ARG LLVM=15

RUN apt-get update && \
    apt-get install -y llvm-${LLVM}-dev clang-${LLVM} libclang-${LLVM}-dev && \
    rm -rf /var/lib/apt/lists/*

CMD cmake -S /src -B . -GNinja -DCMAKE_BUILD_TYPE=Debug && \
    cmake --build . && \
    ctest --output-on-failure .
