FROM ubuntu:20.04

# https://discourse.llvm.org/t/rfc-upgrading-llvms-minimum-required-cmake-version/66193/12
# https://apt.llvm.org/

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y python3-pip wget ca-certificates && \
    wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add - && \
    echo "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-15 main" >> /etc/apt/sources.list && \
    echo "deb-src http://apt.llvm.org/focal/ llvm-toolchain-focal-15 main" >> /etc/apt/sources.list && \
    apt-get update && \
    apt-get install -y gcc g++ llvm-15-dev clang-15 libclang-15-dev clang-format-15 && \
    update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-15 1 && \
    pip3 install "cmake~=3.22" "ninja~=1.10" && \
    apt-get remove -y python3-pip wget ca-certificates && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /src
WORKDIR /build

CMD cmake -S /src -B . -GNinja -DCMAKE_BUILD_TYPE=Debug && \
    cmake --build . && \
    ctest --output-on-failure .
